Add rudimentary documentation for AePPL
aesara-devs/aeppl pull request #213
Opened 2022-12-14 12:44 UTC by rlouf

In this PR I try to add enough documentation to allow anyone to get started with AePPL.

- [ ] Document available distributions
- [ ] Document `joint_logprob` and `conditional_logprob`
- [ ] Document invertible transformations
- [ ] Document other transformations
- [ ] Add an example with multiple backends
- [ ] Demonstrate conditioning on transformed variable

2022-12-15 12:55 UTC, rlouf commented
This is ready for review. I added basic documentation: a list of supported random variables, transforms, scan, mixtures, a home page and a few examples.

2022-12-15 19:21 UTC, brandonwillard approved these changes

2022-12-15 19:23 UTC, brandonwillard commented on docs/source/index.rst
> +.. image:: https://github.com/aesara-devs/aeppl/blob/main/docs/source/logo.png?raw=true
Looks like this might not be rendering: see [here](https://aeppl--213.org.readthedocs.build/en/213/examples.html).

2022-12-15 19:24 UTC, brandonwillard requested changes

2022-12-15 19:24 UTC, brandonwillard commented on docs/source/index.rst
> +   jax_fn = aesara.function([s_vv, y_vv], logprob, mode="JAX")
This isn't showing up either.

2022-12-15 19:24 UTC, brandonwillard commented on docs/source/examples.rst
> +    # -12.956702290497232
Looks like these `testcode` blocks aren't showing up: [here](https://aeppl--213.org.readthedocs.build/en/213/examples.html#the-pert-distribution).

2022-12-15 19:27 UTC, brandonwillard commented on docs/source/api/transforms.rst
> +Clampling
Do we mean "Clipping" or "Clamping"?

2022-12-16 05:54 UTC, brandonwillard submitted a review, later dismissed

2022-12-16 06:33 UTC, merged