Update main example
aesara-devs/aeppl pull request #58
Opened 2021-09-05 16:03 UTC by ricardoV94

Some docstrings and README changes that were missing from #57

2021-09-05 18:52 UTC, brandonwillard requested changes
Since `joint_logprob` will be a likely point-of-entry for most people, we should make its signature more explicit and find a way to reuse parts of the docstring from `factorized_joint_logprob`.

Is anyone aware of a good approach to the latter that doesn't involve copy-pasting text?

2021-09-05 18:52 UTC, brandonwillard commented on aeppl/joint_logprob.py
>      r"""Create a graph representing the joint log-probability/measure of a graph.
```suggestion
    r"""Create a map between variables and their log-probabilities such that the sum is their joint log-probability.
```

2021-09-05 18:52 UTC, brandonwillard commented on aeppl/joint_logprob.py
>      If we create a value variable for ``Y_rv``, i.e. ``y = at.scalar("y")``,
```suggestion
    If we create a value variable for ``Y_rv``, i.e. ``y_vv = at.scalar("y")``,
```

This only adds the `*_vv` suffix convention for value variables.

2021-09-05 18:52 UTC, brandonwillard commented on aeppl/joint_logprob.py
> +    yields the joint log-probability of the two variables.
```suggestion
    the graph of ``factorized_joint_logprob({Y_rv: y_vv})`` is equivalent to the
    conditional probability :math:`\log p(Y = y \mid \sigma^2)`, with a stochastic
    ``sigma2_rv``. If we specify a value variable for ``sigma2_rv``, i.e.
    ``s_vv = at.scalar("s2")``, then ``factorized_joint_logprob({Y_rv: y_vv, sigma2_rv: s_vv})``
    yields the joint log-probability of the two variables.
```

This only adds the `*_vv` suffix convention for value variables.

2021-09-06 08:50 UTC, ricardoV94 commented
> Since `joint_logprob` will be a likely point-of-entry for most people, we should make its signature more explicit and find a way to reuse parts of the docstring from `factorized_joint_logprob`.
> 
> Is anyone aware of a good approach to the latter that doesn't involve copy-pasting text?

Only thing I could find was the `functools.wraps` but doesn't really apply to this. So unless someone has any ideas, either copy-paste or place the docstrings in the `joint_logprob`

2021-09-07 20:43 UTC, brandonwillard approved these changes

2021-09-08 13:55 UTC, merged